--Modificado por Anthony Villalobos 7/9/2026

CREATE TABLE BODEGAS (
    ID_BODEGA NUMBER,
    UBICACION VARCHAR2(100 BYTE),
    PASILLO VARCHAR2(50 BYTE),
    SECCION VARCHAR2(50 BYTE),

    CONSTRAINT PK_BODEGAS
        PRIMARY KEY (ID_BODEGA)
);

CREATE TABLE PROD_CATEGORIA (
    CATEGORIA_ID NUMBER,
    CATEGORIA VARCHAR2(50 BYTE),
    ESTADO NUMBER(1,0),

    CONSTRAINT PK_PROD_CATEGORIA
        PRIMARY KEY (CATEGORIA_ID)
);

CREATE TABLE EMPLEADO (
    ID_EMPLEADO NUMBER,
    NOMBRE VARCHAR2(50 BYTE),
    APELLIDO_P VARCHAR2(50 BYTE),
    APELLIDO_M VARCHAR2(50 BYTE),
    PUESTO VARCHAR2(50 BYTE),
    EMAIL VARCHAR2(100 BYTE),
    TELEFONO NUMBER,
    ESTADO NUMBER(1,0),

    CONSTRAINT PK_EMPLEADO
        PRIMARY KEY (ID_EMPLEADO)
);

CREATE TABLE METODO_ENVIO (
    ID_ENVIO NUMBER,
    TIPO_ENVIO VARCHAR2(50 BYTE),

    CONSTRAINT PK_METODO_ENVIO
        PRIMARY KEY (ID_ENVIO)
);

CREATE TABLE PROVEEDORES (
    ID_PROVEEDOR NUMBER,
    NOMBRE_PROVEEDOR VARCHAR2(100 BYTE),
    TELEFONO NUMBER,
    COD_POSTAL NUMBER,
    EMAIL VARCHAR2(100 BYTE),
    ESTADO NUMBER(1,0),

    CONSTRAINT PK_PROVEEDORES
        PRIMARY KEY (ID_PROVEEDOR)
);

CREATE TABLE PRODUCTOS (
    ID_PRODUCTO NUMBER,
    NOMBRE_PROD VARCHAR2(100 BYTE),
    DESCRIPCION_PROD VARCHAR2(200 BYTE),
    CATEGORIA_ID NUMBER,
    PRECIO_UNIDAD NUMBER(10,2),
    ESTADO NUMBER(1,0),

    CONSTRAINT PK_PRODUCTOS
        PRIMARY KEY (ID_PRODUCTO),

    CONSTRAINT FK_PRODUCTO_CATEGORIA
        FOREIGN KEY (CATEGORIA_ID)
        REFERENCES PROD_CATEGORIA (CATEGORIA_ID)
);

CREATE TABLE INVENTARIO (
    ID_INVENTARIO NUMBER,
    CANT_ACTUAL NUMBER,
    CANT_MIN NUMBER,
    CANT_MAX NUMBER,
    ID_BODEGA NUMBER,

    CONSTRAINT PK_INVENTARIO
        PRIMARY KEY (ID_INVENTARIO),

    CONSTRAINT FK_INVENTARIO_BODEGA
        FOREIGN KEY (ID_BODEGA)
        REFERENCES BODEGAS (ID_BODEGA)
);

CREATE TABLE MOVIMIENTO_INV (
    ID_MOVIMIENTO NUMBER,
    CANTIDAD_MOV NUMBER,
    ID_PRODUCTO NUMBER,
    ID_EMPLEADO NUMBER,
    ID_INVENTARIO NUMBER,
    FECHA DATE,

    CONSTRAINT PK_MOVIMIENTO_INV
        PRIMARY KEY (ID_MOVIMIENTO),

    CONSTRAINT FK_MOV_PRODUCTO
        FOREIGN KEY (ID_PRODUCTO)
        REFERENCES PRODUCTOS (ID_PRODUCTO),

    CONSTRAINT FK_MOV_EMPLEADO
        FOREIGN KEY (ID_EMPLEADO)
        REFERENCES EMPLEADO (ID_EMPLEADO),

    CONSTRAINT FK_MOV_INVENTARIO
        FOREIGN KEY (ID_INVENTARIO)
        REFERENCES INVENTARIO (ID_INVENTARIO)
);

CREATE TABLE ORDEN_COMPRA (
    ID_ORDEN NUMBER,
    NUMERO_FACTURA NUMBER,
    PROVEEDOR_ID NUMBER,
    EMPLEADO_ID NUMBER,
    DESCRIPCION VARCHAR2(200 BYTE),
    METODO_ENVIOID NUMBER,
    FECHA_ENVIO DATE,
    FECHA_ORDEN DATE,

    CONSTRAINT PK_ORDEN_COMPRA
        PRIMARY KEY (ID_ORDEN),

    CONSTRAINT FK_ORDEN_PROVEEDOR
        FOREIGN KEY (PROVEEDOR_ID)
        REFERENCES PROVEEDORES (ID_PROVEEDOR),

    CONSTRAINT FK_ORDEN_EMPLEADO
        FOREIGN KEY (EMPLEADO_ID)
        REFERENCES EMPLEADO (ID_EMPLEADO),

    CONSTRAINT FK_ORDEN_METODO
        FOREIGN KEY (METODO_ENVIOID)
        REFERENCES METODO_ENVIO (ID_ENVIO)
);

CREATE TABLE DETALLE_COMPRA (
    ID_DETALLE NUMBER,
    PRODUCTO_ID NUMBER,
    ORDEN_COMPRA NUMBER,
    CANTIDAD NUMBER,
    DETALLE_PRECIO NUMBER(10,2),

    CONSTRAINT PK_DETALLE_COMPRA
        PRIMARY KEY (ID_DETALLE),

    CONSTRAINT FK_DETALLE_PRODUCTO
        FOREIGN KEY (PRODUCTO_ID)
        REFERENCES PRODUCTOS (ID_PRODUCTO),

    CONSTRAINT FK_DETALLE_ORDEN
        FOREIGN KEY (ORDEN_COMPRA)
        REFERENCES ORDEN_COMPRA (ID_ORDEN)
);


--------------------------------------------------------
--  Consultas auxiliares y de testing
--------------------------------------------------------


--Inserts para testing
--Estos van en el mismo orden en los que se escribieron

--1 
INSERT INTO PROD_CATEGORIA VALUES (1, 'Lacteos', 1);
INSERT INTO PROD_CATEGORIA VALUES (2, 'Bebidas', 1);
INSERT INTO PROD_CATEGORIA VALUES (3, 'Limpieza', 1);
INSERT INTO PROD_CATEGORIA VALUES (4, 'Carnes', 1);
INSERT INTO PROD_CATEGORIA VALUES (5, 'Vegetales', 1);
INSERT INTO PROD_CATEGORIA VALUES (6, 'Panaderia', 1);
INSERT INTO PROD_CATEGORIA VALUES (7, 'Congelados', 1);
INSERT INTO PROD_CATEGORIA VALUES (8, 'Snacks', 1);
INSERT INTO PROD_CATEGORIA VALUES (9, 'Mascotas', 1);
INSERT INTO PROD_CATEGORIA VALUES (10, 'Higiene', 1);

--2
INSERT INTO BODEGAS VALUES (1, 'San Jose', 'A1', 'Norte');
INSERT INTO BODEGAS VALUES (2, 'Heredia', 'A2', 'Sur');
INSERT INTO BODEGAS VALUES (3, 'Cartago', 'B1', 'Este');
INSERT INTO BODEGAS VALUES (4, 'Alajuela', 'B2', 'Oeste');
INSERT INTO BODEGAS VALUES (5, 'Limon', 'C1', 'Centro');
INSERT INTO BODEGAS VALUES (6, 'Puntarenas', 'C2', 'Norte');
INSERT INTO BODEGAS VALUES (7, 'Guanacaste', 'D1', 'Sur');
INSERT INTO BODEGAS VALUES (8, 'Perez Zeledon', 'D2', 'Este');
INSERT INTO BODEGAS VALUES (9, 'Desamparados', 'E1', 'Oeste');
INSERT INTO BODEGAS VALUES (10, 'Escazu', 'E2', 'Centro');

--3
INSERT INTO EMPLEADO VALUES (1,'Jose','Castro','Fernandez','Analista de Inventario','jose.castro@test.com',88881111,1);
INSERT INTO EMPLEADO VALUES (2,'Santiago','Fonseca','Chinchilla','Coordinador de Compras','santiago.fonseca@test.com',88882222,1);
INSERT INTO EMPLEADO VALUES (3,'Kleyber','Vindas','Ocampo','Auxiliar de Bodega','kleyber.vindas@test.com',88883333,1);
INSERT INTO EMPLEADO VALUES (4,'Anthony','Villalobos','Hidalgo','Supervisor de Operaciones','anthony.villalobos@test.com',88884444,1);
INSERT INTO EMPLEADO VALUES (5,'David','Fernandez','Castro','Gestor de Proveedores','david.fernandez@test.com',88885555,1);
INSERT INTO EMPLEADO VALUES (6,'Josue','Ocampo','Vindas','Bodeguero','josue.ocampo@test.com',88886666,1);
INSERT INTO EMPLEADO VALUES (7,'Jose','Chinchilla','Fonseca','Administrador','jose.chinchilla@test.com',88887777,1);
INSERT INTO EMPLEADO VALUES (8,'Santiago','Hidalgo','Villalobos','Encargado de Logistica','santiago.hidalgo@test.com',88888888,1);
INSERT INTO EMPLEADO VALUES (9,'Anthony','Fernandez','Villalobos','Comprador','anthony.fernandez@test.com',87771111,1);
INSERT INTO EMPLEADO VALUES (10,'Kleyber','Villalobos','Ocampo','Supervisor','kleyber.villalobos@test.com',87772222,1);

--4
INSERT INTO METODO_ENVIO VALUES (1,'Terrestre');
INSERT INTO METODO_ENVIO VALUES (2,'Maritimo');
INSERT INTO METODO_ENVIO VALUES (3,'Aereo');
INSERT INTO METODO_ENVIO VALUES (4,'Courier');
INSERT INTO METODO_ENVIO VALUES (5,'Express');
INSERT INTO METODO_ENVIO VALUES (6,'Local');
INSERT INTO METODO_ENVIO VALUES (7,'Nacional');
INSERT INTO METODO_ENVIO VALUES (8,'Internacional');
INSERT INTO METODO_ENVIO VALUES (9,'Urgente');
INSERT INTO METODO_ENVIO VALUES (10,'Economico');

--5
INSERT INTO PROVEEDORES VALUES (1,'Dos Pinos',22221111,10101,'ventas@dospinos.com',1);
INSERT INTO PROVEEDORES VALUES (2,'Coca Cola',22222222,20101,'contacto@cocacola.com',1);
INSERT INTO PROVEEDORES VALUES (3,'Kimberly Clark',22223333,30101,'info@kc.com',1);
INSERT INTO PROVEEDORES VALUES (4,'Cargill',22224444,40101,'ventas@cargill.com',1);
INSERT INTO PROVEEDORES VALUES (5,'Nestle',22225555,50101,'info@nestle.com',1);
INSERT INTO PROVEEDORES VALUES (6,'Unilever',22226666,60101,'contacto@unilever.com',1);
INSERT INTO PROVEEDORES VALUES (7,'Mondelez',22227777,70101,'ventas@mondelez.com',1);
INSERT INTO PROVEEDORES VALUES (8,'Bimbo',22228888,80101,'info@bimbo.com',1);
INSERT INTO PROVEEDORES VALUES (9,'Purina',22229999,90101,'ventas@purina.com',1);
INSERT INTO PROVEEDORES VALUES (10,'Colgate',22230000,10001,'info@colgate.com',1);

--6
INSERT INTO PRODUCTOS VALUES (1,'Leche Entera','Caja 1 litro',1,1250,1);
INSERT INTO PRODUCTOS VALUES (2,'Gaseosa Cola','Botella 2 litros',2,1800,1);
INSERT INTO PRODUCTOS VALUES (3,'Detergente','Bolsa 1kg',3,3500,1);
INSERT INTO PRODUCTOS VALUES (4,'Carne Res','Empaque 1kg',4,6500,1);
INSERT INTO PRODUCTOS VALUES (5,'Tomate','Kilogramo',5,1200,1);
INSERT INTO PRODUCTOS VALUES (6,'Pan Integral','Paquete',6,1800,1);
INSERT INTO PRODUCTOS VALUES (7,'Pizza Congelada','Caja',7,4200,1);
INSERT INTO PRODUCTOS VALUES (8,'Papas Fritas','Bolsa',8,1500,1);
INSERT INTO PRODUCTOS VALUES (9,'Alimento Perro','Saco 2kg',9,8900,1);
INSERT INTO PRODUCTOS VALUES (10,'Pasta Dental','Unidad',10,2900,1);

--7
INSERT INTO INVENTARIO VALUES (1,120,20,250,1);
INSERT INTO INVENTARIO VALUES (2,80,10,200,2);
INSERT INTO INVENTARIO VALUES (3,200,50,400,3);
INSERT INTO INVENTARIO VALUES (4,60,15,150,4);
INSERT INTO INVENTARIO VALUES (5,100,20,300,5);
INSERT INTO INVENTARIO VALUES (6,140,30,250,6);
INSERT INTO INVENTARIO VALUES (7,75,15,180,7);
INSERT INTO INVENTARIO VALUES (8,95,25,220,8);
INSERT INTO INVENTARIO VALUES (9,50,10,120,9);
INSERT INTO INVENTARIO VALUES (10,180,40,350,10);

--8
INSERT INTO ORDEN_COMPRA VALUES (1,1001,1,1,'Compra de lacteos',1,DATE '2026-01-10',DATE '2026-01-08');
INSERT INTO ORDEN_COMPRA VALUES (2,1002,2,2,'Compra bebidas',2,DATE '2026-01-12',DATE '2026-01-09');
INSERT INTO ORDEN_COMPRA VALUES (3,1003,3,3,'Compra limpieza',3,DATE '2026-01-15',DATE '2026-01-11');
INSERT INTO ORDEN_COMPRA VALUES (4,1004,4,4,'Compra carnes',4,DATE '2026-01-18',DATE '2026-01-12');
INSERT INTO ORDEN_COMPRA VALUES (5,1005,5,5,'Compra vegetales',5,DATE '2026-01-20',DATE '2026-01-13');
INSERT INTO ORDEN_COMPRA VALUES (6,1006,6,6,'Compra varios',6,DATE '2026-01-21',DATE '2026-01-14');
INSERT INTO ORDEN_COMPRA VALUES (7,1007,7,7,'Compra snacks',7,DATE '2026-01-22',DATE '2026-01-15');
INSERT INTO ORDEN_COMPRA VALUES (8,1008,8,8,'Compra panaderia',8,DATE '2026-01-23',DATE '2026-01-16');
INSERT INTO ORDEN_COMPRA VALUES (9,1009,9,9,'Compra mascotas',9,DATE '2026-01-24',DATE '2026-01-17');
INSERT INTO ORDEN_COMPRA VALUES (10,1010,10,10,'Compra higiene',10,DATE '2026-01-25',DATE '2026-01-18');

--9
INSERT INTO MOVIMIENTO_INV VALUES (1,20,1,1,1,DATE '2026-02-01');
INSERT INTO MOVIMIENTO_INV VALUES (2,-10,2,2,2,DATE '2026-02-02');
INSERT INTO MOVIMIENTO_INV VALUES (3,15,3,3,3,DATE '2026-02-03');
INSERT INTO MOVIMIENTO_INV VALUES (4,-5,4,4,4,DATE '2026-02-04');
INSERT INTO MOVIMIENTO_INV VALUES (5,30,5,5,5,DATE '2026-02-05');
INSERT INTO MOVIMIENTO_INV VALUES (6,-8,6,6,6,DATE '2026-02-06');
INSERT INTO MOVIMIENTO_INV VALUES (7,25,7,7,7,DATE '2026-02-07');
INSERT INTO MOVIMIENTO_INV VALUES (8,-12,8,8,8,DATE '2026-02-08');
INSERT INTO MOVIMIENTO_INV VALUES (9,18,9,9,9,DATE '2026-02-09');
INSERT INTO MOVIMIENTO_INV VALUES (10,-7,10,10,10,DATE '2026-02-10');

--10
INSERT INTO DETALLE_COMPRA VALUES (1,1,1,50,1250);
INSERT INTO DETALLE_COMPRA VALUES (2,2,2,40,1800);
INSERT INTO DETALLE_COMPRA VALUES (3,3,3,30,3500);
INSERT INTO DETALLE_COMPRA VALUES (4,4,4,25,6500);
INSERT INTO DETALLE_COMPRA VALUES (5,5,5,60,1200);
INSERT INTO DETALLE_COMPRA VALUES (6,6,6,45,1800);
INSERT INTO DETALLE_COMPRA VALUES (7,7,7,20,4200);
INSERT INTO DETALLE_COMPRA VALUES (8,8,8,35,1500);
INSERT INTO DETALLE_COMPRA VALUES (9,9,9,15,8900);
INSERT INTO DETALLE_COMPRA VALUES (10,10,10,55,2900);

--Esto era para hacer testing de las columnas
SELECT * FROM BODEGAS;

SELECT * FROM PROD_CATEGORIA;

SELECT * FROM EMPLEADO;

SELECT * FROM METODO_ENVIO;

SELECT * FROM PROVEEDORES;

SELECT * FROM PRODUCTOS;

SELECT * FROM INVENTARIO;

SELECT * FROM MOVIMIENTO_INV;

SELECT * FROM ORDEN_COMPRA;

SELECT * FROM DETALLE_COMPRA;

