-- Dims


CREATE TABLE DIM_PROVEEDOR (
    PRV_ID              INTEGER NOT NULL
        CONSTRAINT PK_PRV_ID PRIMARY KEY,
    PRV_NOMBRE          VARCHAR2(100) NOT NULL,
    PRV_TELEFONO        NUMBER,
    PRV_COD_POSTAL      NUMBER,
    PRV_EMAIL           VARCHAR2(100)
);

CREATE TABLE DIM_PRODUCTO (
    PRD_ID              INTEGER NOT NULL
        CONSTRAINT PK_PRD_ID PRIMARY KEY,
    PRD_NOMBRE          VARCHAR2(100) NOT NULL,
    PRD_DESCRIPCION     VARCHAR2(200),
    PRD_CATEGORIA_ID    INTEGER,
    PRD_PRECIO_UNIDAD   NUMBER(10,2)
);

CREATE TABLE DIM_EMPLEADO (
    EMP_ID              INTEGER NOT NULL
        CONSTRAINT PK_EMP_ID PRIMARY KEY,
    EMP_NOMBRE          VARCHAR2(50),
    EMP_APELLIDO_P      VARCHAR2(50),
    EMP_APELLIDO_M      VARCHAR2(50),
    EMP_PUESTO          VARCHAR2(50),
    EMP_EMAIL           VARCHAR2(100),
    EMP_TELEFONO        NUMBER
);

CREATE TABLE DIM_ORDEN_COMPRA (
    ORD_ID              INTEGER NOT NULL
        CONSTRAINT PK_ORD_ID PRIMARY KEY,
    ORD_NUMERO_FACTURA  NUMBER,
    ORD_METODO_ENVIO_ID NUMBER,
    ORD_FECHA_ENVIO     DATE,
    ORD_FECHA_ORDEN     DATE
);

CREATE TABLE DIM_FECHA (
    FEC_ID              INTEGER NOT NULL
        CONSTRAINT PK_FEC_ID PRIMARY KEY,
    FEC_FECHA           DATE NOT NULL
);


-- Hechos


CREATE TABLE FACT_INV_TRANSACCION (
    INV_PRV_ID          INTEGER NOT NULL,
    INV_PRD_ID          INTEGER NOT NULL,
    INV_EMP_ID          INTEGER NOT NULL,
    INV_ORD_ID          INTEGER NOT NULL,
    INV_FEC_ID          INTEGER NOT NULL,

    INV_ID_MOVIMIENTO   INTEGER NOT NULL,
    INV_ID_INVENTARIO   INTEGER NOT NULL,
    INV_CANTIDAD_MOV    NUMBER NOT NULL,

    CONSTRAINT PK_INV_TRANSACCION
    PRIMARY KEY (
        INV_PRV_ID,
        INV_PRD_ID,
        INV_EMP_ID,
        INV_ORD_ID,
        INV_FEC_ID,
        INV_ID_MOVIMIENTO
    ),

    CONSTRAINT FK_INV_PRV
        FOREIGN KEY (INV_PRV_ID)
        REFERENCES DIM_PROVEEDOR(PRV_ID),

    CONSTRAINT FK_INV_PRD
        FOREIGN KEY (INV_PRD_ID)
        REFERENCES DIM_PRODUCTO(PRD_ID),

    CONSTRAINT FK_INV_EMP
        FOREIGN KEY (INV_EMP_ID)
        REFERENCES DIM_EMPLEADO(EMP_ID),

    CONSTRAINT FK_INV_ORD
        FOREIGN KEY (INV_ORD_ID)
        REFERENCES DIM_ORDEN_COMPRA(ORD_ID),

    CONSTRAINT FK_INV_FEC
        FOREIGN KEY (INV_FEC_ID)
        REFERENCES DIM_FECHA(FEC_ID)
);