--------------------------------------------
--Consulta de creacion del ETL del SA
--------------------------------------------

--Referencia del porque usar el to_char:
--https://sites.google.com/site/jmdstips/oracle/to_char-function
--Usamos TO_CHAR solo para valores de tipo de date, para asi poder darle un formato varchar2 (dd/mm/aaaa -> AAAAMMDD)


CREATE OR REPLACE PACKAGE PG_ETL_SA AS
--Inicio de los funciones para cargar los datos del ER
    PROCEDURE CARGA_PROVEEDORES; 
    PROCEDURE CARGA_EMPLEADO;
    PROCEDURE CARGA_PRODUCTOS;
    PROCEDURE CARGA_ORDEN_COMPRA;
    PROCEDURE CARGA_MOVIMIENTO_INV;
    PROCEDURE CARGA_DATOS;
END PG_ETL_SA;
/

--Creacion del body.
CREATE OR REPLACE PACKAGE BODY PG_ETL_SA AS
    PROCEDURE CARGA_PROVEEDORES AS --Primer proceso
    BEGIN 
        INSERT INTO INVENTARIOSA.SA_PROVEEDOR(ID_PROVEEDOR, NOMBRE_PROVEEDOR, TELEFONO, COD_POSTAL, EMAIL, ESTADO)
        SELECT ID_PROVEEDOR, NOMBRE_PROVEEDOR, TELEFONO, COD_POSTAL, EMAIL, ESTADO
        FROM INVENTARIO.PROVEEDORES
        WHERE ID_PROVEEDOR NOT IN (SELECT ID_PROVEEDOR FROM INVENTARIOSA.SA_PROVEEDOR); 
        --El filtro de estado lo vamos a hacer hasta el etl del dw, en caso de que esos records los ocupemos a futuro
    END CARGA_PROVEEDORES;

    PROCEDURE CARGA_EMPLEADO AS --Segundo proceso
    BEGIN
        INSERT INTO INVENTARIOSA.SA_EMPLEADO(ID_EMPLEADO, NOMBRE, APELLIDO_P, APELLIDO_M, PUESTO, EMAIL, TELEFONO, ESTADO)
        SELECT ID_EMPLEADO, NOMBRE, APELLIDO_P, APELLIDO_M, PUESTO, EMAIL, TELEFONO, ESTADO
        FROM INVENTARIO.EMPLEADO
        WHERE ID_EMPLEADO NOT IN (SELECT ID_EMPLEADO FROM INVENTARIOSA.SA_EMPLEADO);
    END CARGA_EMPLEADO;

    PROCEDURE CARGA_PRODUCTOS AS --Tercer proceso
    BEGIN
        INSERT INTO INVENTARIOSA.SA_PRODUCTO(ID_PRODUCTO, NOMBRE_PROD, DESCRIPCION_PROD, CATEGORIA_ID, PRECIO_UNIDAD, ESTADO)
        SELECT ID_PRODUCTO, NOMBRE_PROD, DESCRIPCION_PROD, CATEGORIA_ID, PRECIO_UNIDAD, ESTADO
        FROM INVENTARIO.PRODUCTOS
        WHERE ID_PRODUCTO NOT IN (SELECT ID_PRODUCTO FROM INVENTARIOSA.SA_PRODUCTO);
    END CARGA_PRODUCTOS;

    PROCEDURE CARGA_ORDEN_COMPRA AS --Cuarto proceso
    BEGIN
        INSERT INTO INVENTARIOSA.SA_ORDEN_COMPRA(ID_ORDEN, NUMERO_FACTURA, PROVEEDOR_ID, EMPLEADO_ID, DESCRIPCION, METODO_ENVIO_ID, FECHA_ENVIO, FECHA_ORDEN)
        SELECT ID_ORDEN, NUMERO_FACTURA, PROVEEDOR_ID, EMPLEADO_ID, DESCRIPCION, METODO_ENVIOID, TO_CHAR(FECHA_ENVIO, 'YYYYMMDD'), TO_CHAR(FECHA_ORDEN, 'YYYYMMDD')
        FROM INVENTARIO.ORDEN_COMPRA
        WHERE ID_ORDEN NOT IN (SELECT ID_ORDEN FROM INVENTARIOSA.SA_ORDEN_COMPRA);
    END CARGA_ORDEN_COMPRA;

    PROCEDURE CARGA_MOVIMIENTO_INV AS -- Quinto proceso
    BEGIN
        INSERT INTO INVENTARIOSA.SA_MOVIMIENTO_INV(ID_MOVIMIENTO, CANTIDAD_MOV, ID_PRODUCTO, ID_EMPLEADO, ID_INVENTARIO, FECHA)
        SELECT ID_MOVIMIENTO, CANTIDAD_MOV, ID_PRODUCTO, ID_EMPLEADO, ID_INVENTARIO, TO_CHAR(FECHA, 'YYYYMMDD')
        FROM INVENTARIO.MOVIMIENTO_INV
        WHERE ID_MOVIMIENTO NOT IN (SELECT ID_MOVIMIENTO FROM INVENTARIOSA.SA_MOVIMIENTO_INV);
    END CARGA_MOVIMIENTO_INV;

    PROCEDURE CARGA_DATOS AS --Proceso principal
    BEGIN
        CARGA_PROVEEDORES; --1
        CARGA_EMPLEADO; --2
        CARGA_PRODUCTOS; --3
        CARGA_ORDEN_COMPRA; --4
        CARGA_MOVIMIENTO_INV; --5
        COMMIT;
    END CARGA_DATOS;
END PG_ETL_SA;
/

EXECUTE PG_ETL_SA.CARGA_DATOS;